kind: Deployment
apiVersion: apps/v1
metadata:
  name: freeradius
spec:
  replicas: 1
  selector:
    matchLabels:
      run: freeradius
  template:
    metadata:
      labels:
        run: freeradius
    spec:
      containers:
        - name: freeradius
          image: 'linuxgui/freeradius:latest'
          ports:
            - containerPort: 1812
              protocol: UDP
            - containerPort: 1813
              protocol: UDP